define([
    'js/World',
    'js/Extendable',
    'js/Line',
    'js/LineStar',
    'js/Stripes',
    'js/IterDraw',
    'js/Square',
    'js/Circle',
    'js/CircleStripes',
    'js/Triangle',
    'js/Hexagon',
    'js/ExpandingShapes',
    'js/State',
    'js/KeyHandler',
    'js/SoundData'
], function(
    World,
    Extendable,
    Line,
    LineStar,
    Stripes,
    IterDraw,
    Square,
    Circle,
    CircleStripes,
    Triangle,
    Hexagon,
    ExpandingShapes,
    Sequence,
    KeyHandler,
    SoundData
) {
    return {
        World: World,
        Extendable: Extendable,
        IterDraw: IterDraw,
        Line: Line,
        Square: Square,
        LineStar: LineStar,
        Stripes: Stripes,
        Circle: Circle,
        CircleStripes: CircleStripes,
        Triangle: Triangle,
        Hexagon: Hexagon,
        ExpandingShapes: ExpandingShapes,
        Sequence: Sequence,
        KeyHandler: KeyHandler,
        SoundData: SoundData
    };
});
